# Generated by Django 5.1.6 on 2025-03-08 10:08

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(db_index=True, max_length=128)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=256)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_composite', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_notification', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='channel.channel')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'local_products',
                'unique_together': {('sku', 'channel')},
            },
        ),
    ]
