# Generated by Django 5.1.6 on 2025-06-01 17:40

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organization_email_organization_expiration_date_and_more'),
        ('store', '0002_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('marketplace_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('marketplace', models.CharField(blank=True, max_length=128)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=128)),
                ('category', models.TextField(blank=True, max_length=512, null=True)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('fbm', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to='store.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'marketplace_products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, max_length=512, null=True)),
                ('sku', models.CharField(db_index=True, max_length=128)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=256)),
                ('style', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('purchase_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('selling_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('is_composite', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, max_length=2048, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_notification', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'local_products',
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.CharField(choices=[('AMAZON', 'Amazon'), ('BIG_COMMERCE', 'BigCommerce'), ('EBAY', 'eBay'), ('OTTO', 'Otto'), ('SHEIN', 'Shein'), ('SHOPIFY', 'Shopify'), ('TEMU', 'Temu'), ('TIKTOK_SHOP', 'TikTok Shop'), ('WOOCOMMERCE', 'WooCommerce'), ('OTHER', 'Other')], max_length=128)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='store.store')),
                ('marketplace_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='product.marketplaceproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'mappings',
                'unique_together': {('product', 'marketplace_product', 'store')},
            },
        ),
    ]
