# Generated by Django 5.1.6 on 2025-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='marketplace',
            field=models.CharField(blank=True, choices=[('AMAZON', 'Amazon'), ('BIG_COMMERCE', 'BigCommerce'), ('EBAY', 'eBay'), ('OTTO', 'Otto'), ('SHEIN', 'Shein'), ('SHOPIFY', 'Shopify'), ('TEMU', 'Temu'), ('TIKTOK_SHOP', 'TikTok Shop'), ('WOOCOMMERCE', 'WooCommerce'), ('OTHER', 'Other')], default='OTHER', max_length=128),
        ),
    ]
