# Generated by Django 5.1.6 on 2025-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
