# Generated by Django 5.1.6 on 2025-03-07 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_order_id', models.CharField(db_index=True, help_text='Unique order ID from the channel.', max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current payment status of the order.', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Method used for payment (e.g., Credit Card, PayPal).', max_length=50)),
                ('purchase_date', models.DateTimeField(help_text='Date and time the order was placed.')),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR).', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount.', max_digits=12)),
                ('company_uid', models.CharField(db_index=True, help_text='Unique identifier for the company.', max_length=36)),
                ('market_place', models.CharField(blank=True, help_text='Marketplace name (e.g., Amazon, eBay).', max_length=50, null=True)),
                ('dispatch_status', models.CharField(choices=[('OPEN_ORDER', 'Open Order'), ('CLOSED', 'Closed'), ('DISPATCHED', 'Dispatched'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='OPEN_ORDER', help_text='Current dispatch status of the order.', max_length=20)),
                ('dispatch_identifier', models.CharField(blank=True, help_text='Identifier for dispatch tracking.', max_length=128)),
                ('dispatched_by', models.CharField(blank=True, help_text='Entity or person who dispatched the order.', max_length=128)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='Date and time of dispatch.', null=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text='Date and time of shipment.', null=True)),
                ('order_meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the order.', null=True)),
                ('channel', models.ForeignKey(blank=True, help_text='The sales channel this order originates from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_orders', to='channel.channel')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_sku', models.CharField(blank=True, help_text='SKU from the remote channel.', max_length=128, null=True)),
                ('local_sku', models.CharField(blank=True, help_text='Local SKU if mapped.', max_length=128, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items ordered.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price for this item (price * quantity).', max_digits=12)),
                ('position_item_ids', models.JSONField(blank=True, default=list, help_text='List of position item IDs (replaced ArrayField for portability).', null=True)),
                ('picked_sku', models.CharField(blank=True, help_text='SKU of the picked item.', max_length=128, null=True)),
                ('picked_at', models.DateTimeField(blank=True, help_text='Date and time the item was picked.', null=True)),
                ('picked_item_type', models.CharField(blank=True, choices=[('EXACT_ITEM', 'Exact Item'), ('EXCHANGE_ITEM', 'Exchange Item')], help_text='Type of picked item.', max_length=20, null=True)),
                ('packed_sku', models.CharField(blank=True, help_text='SKU of the packed item.', max_length=128, null=True)),
                ('packed_at', models.DateTimeField(blank=True, help_text='Date and time the item was packed.', null=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_name', models.CharField(blank=True, help_text='Name of the buyer.', max_length=255)),
                ('address1', models.CharField(blank=True, help_text='Primary address line.', max_length=255)),
                ('address2', models.CharField(blank=True, help_text='Secondary address line.', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City of the shipping address.', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province.', max_length=100)),
                ('post_code', models.CharField(blank=True, help_text='Postal/ZIP code.', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country of the shipping address.', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='External reference ID for the address.', max_length=128, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, null=True)),
                ('order', models.OneToOneField(help_text='The order this shipping address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Shipping Address',
                'verbose_name_plural': 'Order Shipping Addresses',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['channel_order_id', 'company_uid'], name='order_order_channel_b0fd31_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['remote_sku', 'local_sku'], name='order_order_remote__d5e314_idx'),
        ),
    ]
