# Generated by Django 5.1.6 on 2025-05-31 17:37

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organization_email_organization_expiration_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('auth_type', models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('OAUTH', 'OAuth'), ('OAUTH2', 'OAuth2'), ('TOKEN', 'Token')], default='BASIC', max_length=20)),
                ('store_type', models.CharField(max_length=20)),
                ('store_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('marketplace', models.CharField(blank=True, choices=[('AMAZON', 'Amazon'), ('BIG_COMMERCE', 'BigCommerce'), ('EBAY', 'eBay'), ('OTTO', 'Otto'), ('SHEIN', 'Shein'), ('SHOPIFY', 'Shopify'), ('TEMU', 'Temu'), ('TIKTOK_SHOP', 'TikTok Shop'), ('WOOCOMMERCE', 'WooCommerce'), ('OTHER', 'Other')], default='OTHER', max_length=128)),
                ('shop_url', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('max_stock', models.PositiveIntegerField(blank=True, default=0)),
                ('report_ref', models.JSONField(blank=True, default=dict)),
                ('report_sorted_by', models.CharField(blank=True, max_length=128)),
                ('is_authorized', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('access_token_expiry', models.BigIntegerField(blank=True, default=0, null=True)),
                ('refresh_token_expiry', models.BigIntegerField(blank=True, default=0, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order_sync', models.BooleanField(blank=True, default=False)),
                ('inventory_sync', models.BooleanField(default=False)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
