# Generated by Django 5.1.6 on 2025-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='The date when the subscription expires.', null=True, verbose_name='Subscription Expiration Date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription',
            field=models.BooleanField(default=False, help_text='Indicates if the organization has a subscription.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Profile Image'),
        ),
    ]
