# Generated by Django 5.1.6 on 2025-03-07 07:01

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('VERIFIED', 'Verified')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_type', models.CharField(max_length=20)),
                ('channel_state', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('shop_url', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('channel_max_stock', models.PositiveIntegerField(blank=True)),
                ('report_ref', models.JSONField(blank=True, null=True)),
                ('report_sorted_by', models.CharField(blank=True, max_length=128)),
                ('is_authorized', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('channel_metadata', models.JSONField(blank=True, null=True)),
                ('order_sync', models.BooleanField(blank=True, default=False)),
                ('inventory_sync', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_channels', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entry_by', to=settings.AUTH_USER_MODEL, verbose_name='entry by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'Channels',
            },
        ),
    ]
